### ISSUE TITLE
Scorching ray stuck on second missile

### ISSUE THREAD

**Issue by Wokeye27** [teroparvinen/foundry-wire-srd#1]
Hi - awesome mod! 

When I run Scorching Ray (3 missiles) it seems to run the first one OK, then rolls OK for the second but will then not let me proceed to press the tick or cross (hit/miss). 
![image](https://user-images.githubusercontent.com/77101610/206140898-ee9cd624-093a-41cc-88fc-9d1962ae57fc.png)

**Comment by teroparvinen** [comment]
Can you check the error console for any errors. Other than that, please try disabling all other modules except stuff relevant to WIRE (there's a bug that causes errors if DAE is not enabled currently) and see if that helps.
