### ISSUE TITLE
Suggestion: Life Transference

### ISSUE THREAD

**Issue by DreamingHero1997** [teroparvinen/foundry-wire-srd#2]
Hey I was wondering if you could add Life Transference to the next update

**Comment by teroparvinen** [comment]
That spell is not in the SRD, but this is how I would implement it mechanically (with WIRE 0.10.8, please see note about a bug below):

- Make it a healing spell with 4d8 healing
- Give it an active effect with an application phase "While resolving outcome"
- Add an effect row: `flags.wire.grants.damage.multiplier.type.healing` Multiply, value: 2
- Give it a macro that inflicts the healing amount as damage to the caster:

```
this.registerFlowStep("damageSelf", true, activation => {
    const actor = activation.item.actor;
    const damage = activation.damageParts.total;
    game.wire.DamageCard.makeForActor(actor, actor, damage);
});

return this.defaultFlow(
    this.performCustomStep("damageSelf")
)
```

There is a bug in WIRE 0.10.7 that causes the `activation.damageParts.total` to fail (reading the amount of damage caused). I have fixed it and it will be in the next update, after which this recipe should do it.

This will also be added to the [WIRE examples](https://github.com/teroparvinen/foundry-wire-examples) module, so make sure to keep an eye on that.
