### ISSUE TITLE
Request: Life Drain

### ISSUE THREAD

**Issue by DreamingHero1997** [teroparvinen/foundry-wire-srd#3]
Could you make the life drain attack, used by creatures such as the specter?

**Comment by teroparvinen** [comment]
This requires information about the triggering condition's details, which was not available with WIRE 0.10.8. I have made it available in 0.10.9 (currently still unreleased) and it will work.

Here's the recipe (will be in an upcoming release of the SRD):

- Add a condition on the item: This attack hits → Activate delayed effects (this will make the save occur)
- Create an effect on the item
    - Application phase: Delayed
    - Allow multiple applications: Checked
    - Treat the effect value as a roll: Checked
- Create an effect change row with a key of `system.attributes.hp.tempmax` (requires DAE, which is recommended at this point anyway), ADD, Effect value `-@condition.details.damage.total` (this is the info currently missing)
